#!/usr/bin/env node
/**
 * Install pre-commit hook that runs biome check on staged files.
 * Uses git's built-in hook system (no husky/lefthook needed).
 *
 * Idempotent — safe to run multiple times.
 */

const fs = require('node:fs')
const path = require('node:path')

const HOOK = `#!/usr/bin/env sh
# Pre-commit hook: run biome check on staged files
# Generated by scripts/install-hooks.js

STAGED=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\\.(ts|tsx|js|jsx|json)$$' || true)

if [ -z "$STAGED" ]; then
  exit 0
fi

echo "Running biome check on staged files..."
npx --no-install biome check --no-errors-on-unmatched $STAGED

if [ $? -ne 0 ]; then
  echo ""
  echo "biome check failed. To fix:"
  echo "  pnpm check       # auto-fix what can be fixed"
  echo "  git commit --no-verify   # skip this hook (not recommended)"
  exit 1
fi
`

const hookPath = path.join(__dirname, '..', '.git', 'hooks', 'pre-commit')

fs.writeFileSync(hookPath, HOOK, { mode: 0o755 })
console.log(`Installed pre-commit hook: ${hookPath}`)
